//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_School.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStudent()
        {
            this.tblScores = new HashSet<tblScore>();
        }
    
        public int stdId { get; set; }
        public string stdNameSurname { get; set; }
        public string stdImage { get; set; }
        public string stdGender { get; set; }
        public Nullable<byte> stdSocialClub { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblScore> tblScores { get; set; }
        public virtual tblSocialClub tblSocialClub { get; set; }
    }
}
